name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Lint & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm ci

      - name: Run linters
        run: |
          npm run lint && npm run check

      - name: Run tests
        run: |
          npm run test

      - name: Run build
        run: |
          npm run build
