# This is a basic workflow to automatically build a Svelte app and deploy it to GitHub Pages

name: Push
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore
      - LICENSE
    branches:
      - 'main'

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          npm ci

      - name: Test
        run: |
          npm run test

      - name: Build
        run: |
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./build
          github_token: ${{ secrets.GITHUB_TOKEN }}
          enable_jekyll: false
